name: Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        with:
          target_branch: 'gh-pages'
          pre_build_commands: git config --global http.version HTTP/1.1; apk fetch git-lfs;
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          JEKYLL_ENV: production
